In [1]:
import pandas
df = pandas.read_pickle('../data/questions/Questions54Top10.pkl')

In [2]:
df.head()

,qid,title,desc_text,desc_code,creation_date,clean_tags
0,67881547,Formating a sum reduce function in Python,I'm trying to format the result of a sum funct...,from functools import reduce def sum_equation(...,2021-06-08T04:46:55.547,['python']
1,67881569,"Functionallity (supposedly) of shutil.which(""f...",I have a github project for my app Scout. I us...,NaN,2021-06-08T04:49:10.447,['python']
2,67881560,How to create a Telegram Bot Inline Keyboard M...,I have created a Python Telegram Bot with an I...,NaN,2021-06-08T04:48:19.650,['python']
3,67881549,app.use() and router.post() is not working,My app.use() is not working.It shows 'Cannot P...,**app.js** const express=require('express'); c...,2021-06-08T04:47:13.633,['node.js']
4,67881553,Remove an object inside an array based on value,I would like to ask how to remove an element i...,"[ { ""id"": 1, ""sender"": ""a"", ""receiver"": ""b"" },...",2021-06-08T04:47:39.353,['javascript']

In [4]:
df.tail()

,qid,title,desc_text,desc_code,creation_date,clean_tags
221043,69060955,How to prevent arithmetic overflow from corrup...,I have a class that has two int fields x and y...,class MyClass { private int x; private int y; ...,2021-09-05T06:10:22.667,['c#']
221044,69061016,How to add AI recommendation feature in to and...,can I know how can I add AI recommendation fea...,NaN,2021-09-05T06:20:14.037,['android']
221045,69061013,How do I make input range display number?,I want this slider to display the number. At t...,NaN,2021-09-05T06:19:41.830,['html']
221046,69061026,how to accept when MultipartFile is empty?,For the below code when I am trying to hit thr...,"@PostMapping(""add"") public ResponseEntity<JSON...",2021-09-05T06:22:26.807,['java']
221047,69061027,crawl website that uses php session and change...,I want to crawl the following page: https://db...,url = 'https://db.aa419.org/fakebankslist.php'...,2021-09-05T06:22:30.310,"['python', 'php']"

In [5]:
train_size = 0.7
train_dataset = df.sample(frac=train_size, random_state=200)
test_dataset = df.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)


valid_dataset = test_dataset.sample(frac=0.5, random_state=42)
test_dataset = test_dataset.drop(valid_dataset.index).reset_index(drop=True)
valid_dataset = valid_dataset.reset_index(drop=True)

print("FULL Dataset: {}".format(df.shape))
print("TRAIN Dataset: {}".format(train_dataset.shape))
print("TEST Dataset: {}".format(test_dataset.shape))
print("VALID Dataset: {}".format(valid_dataset.shape))

train_dataset.to_csv("../data/questions/Train_Questions54.csv", index=False)
valid_dataset.to_csv("../data/questions/Valid_Questions54.csv", index=False)
test_dataset.to_csv("../data/questions/Test_Questions54.csv", index=False)

FULL Dataset: (221048, 6)
TRAIN Dataset: (154734, 6)
TEST Dataset: (33157, 6)
VALID Dataset: (33157, 6)

In [6]:
train_dataset.to_pickle("../data/questions/Train_Questions54Top10.pkl")
valid_dataset.to_pickle("../data/questions/Valid_Questions54Top10.pkl")
test_dataset.to_pickle("../data/questions/Test_Questions54Top10.pkl")

In [8]:
df_train = pandas.read_pickle("../data/questions/Train_Questions54Top10.pkl")
# valid_dataset.to_pickle("../data/questions/Valid_Questions54Top10.pkl")
# test_dataset.to_pickle("../data/questions/Test_Questions54Top10.pkl")

In [9]:
df_train.head()

,qid,title,desc_text,desc_code,creation_date,clean_tags
0,68945060,React make useState initial value conditional,I am trying to set initial state based on data...,"const Calculate({data}) => { const [number, se...",2021-08-26T20:39:33.023,"['reactjs', 'javascript']"
1,68111792,Elevate application to administration by limit...,Currently i'm busy creating an application for...,NaN,2021-06-24T08:01:27.023,['c#']
2,68303073,Nested Router in ReactJS - Show blank page on ...,I am a beginner in ReactJS and React Router an...,"import React from ""react""; import { Router, Sw...",2021-07-08T13:58:04.570,"['reactjs', 'javascript']"
3,68953821,How to map POCO into Record using AutoMapper,I'm using AutoMapper 10.1.1 with .NET 6 (previ...,using AutoMapper; using FluentAssertions; usin...,2021-08-27T12:56:01.197,['c#']
4,68758004,Header detail footer report in python like out...,I am trying to create a report from my datafra...,NaN,2021-08-12T13:01:44.307,['python']